FROM node:18

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils

WORKDIR /usr/src/app

COPY application/backend/accounting/campaign-promotion/package.json application/backend/accounting/campaign-promotion/yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN cd application/backend/accounting/campaign-promotion && yarn build

EXPOSE 8011

CMD ["yarn","start"]