version: '3.8'

services:
  networkux:
    container_name: networkux
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    volumes:
      - networkux:/var/lib/pgadmin
    ports:
      - "8891:80"
    networks:
      - networkdb-networkux-network
  networkdb:
    container_name: networkdb
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - networkdb:/var/lib/postgresql/data
    networks:
      - networkdb-networkux-network

networks: 
  networkdb-networkux-network:
    driver: bridge

volumes:
  networkdb:
  networkux: