version: '3'

services:
  pg-admin:
    container_name: pg_admin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres
    ports:
      - "5050:80"

  postgres:
      container_name: postgres_container
      image: postgres:15
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        PG_DATA: /data/postgres
      volumes:
        - postgres:/data/postgres
      ports:
        - "5432:5432"
      networks:
        - postgres
      restart: unless-stopped

networks:
  postgres:
    driver: bridge
  
volumes:
  postgres:
  pgadmin: