version: '3.8'

services:
  load-balancer:
      image: nginx
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: '0.1'
            memory: '128M'
      networks:
        - gateway_network

networks:
  gateway_network:
    external: true