FROM node:18

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils

WORKDIR /usr/src/app

COPY application/backend/accounting/promotion-proposals/package.json application/backend/accounting/promotion-proposals/yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN cd application/backend/accounting/promotion-proposals && yarn build

EXPOSE 8012

CMD ["yarn","start"]