FROM node:18

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils

WORKDIR /usr/src/app

COPY ./application/backend/utilities/shared ./shared
COPY ./application/backend/cross-cutting/gateway ./

RUN yarn install 
RUN yarn add ./shared

RUN yarn build

EXPOSE 8000

CMD ["yarn", "start"]