version: '3.8'

services:
  redis_gateway:
    container_name: redis_gateway
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ~/.docker-conf/redis/data/:/var/lib/redis/
      - ~/.docker-conf/redis/log/:/var/log/redis

  gateway_app: 
    build: 
      context: .
      network: host
      dockerfile: ./dockerfile
    deploy:
      replicas: 3
    environment:
      - PORT=8000
    command: yarn run start
    networks:
      - gateway-network
      
networks:
  gateway-network: