version: '3.8'

services:
  redis_gateway:
    container_name: redis_gateway
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ~/.docker-conf/redis/data/:/var/lib/redis/
      - ~/.docker-conf/redis/log/:/var/log/redis
    networks:
      - redis_network_gateway

networks:
  redis_network_gateway:
    driver: bridge