version: '3.8'

services:
  rabbit_mq_journal:
    container_name: rabbit_mq_journal
    image: rabbitmq:3.12-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_network_journal

networks:
  rabbitmq_network_journal:
    driver: bridge