FROM node:18

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils

WORKDIR /usr/src/app

COPY application/backend/commerce/chapter/package.json application/backend/commerce/chapter/yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN cd application/backend/commerce/chapter && yarn build

EXPOSE 8005

CMD ["yarn","start"]