version: '3.8'

services:
  chapterux:
    container_name: chapterux
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    volumes:
      - chapterux:/var/lib/pgadmin
    ports:
      - "8894:80"
    networks:
      - chapter-db-ux-network
  chapterdb:
    container_name: chapterdb
    image: postgres
    restart: always
    ports:
      - "5437:5432"
    environment:
      POSTGRES_chapter: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - chapterdb:/var/lib/postgresql/data
    networks:
      - chapter-db-ux-network

networks: 
  chapter-db-ux-network:
    driver: bridge

volumes:
  chapterdb:
  chapterux: