version: '3.8'

services:
  pageux:
    container_name: pageux
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    volumes:
      - pageux:/var/lib/pgadmin
    ports:
      - "8895:80"
    networks:
      - page-db-ux-network
  pagedb:
    container_name: pagedb
    image: postgres
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_page: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pagedb:/var/lib/postgresql/data
    networks:
      - page-db-ux-network
  page_app: 
    build: 
      context: .
      network: host
      dockerfile: ./dockerfile
    deploy:
      replicas: 3
    environment:
      - PORT=8007
    command: yarn run start
    networks:
      - gateway_gateway-network

networks: 
  page-db-ux-network:
    driver: bridge
  gateway_gateway-network:

volumes:
  pagedb:
  pageux: