FROM node:18

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils

WORKDIR /usr/src/app

COPY application/backend/accounting/wallet/package.json application/backend/accounting/wallet/yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN cd application/backend/accounting/wallet && yarn build

EXPOSE 8007

CMD ["yarn","start"]