version: '3.8'

services:
  walletux:
    container_name: walletux
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    volumes:
      - walletux:/var/lib/pgadmin
    ports:
      - "8900:80"
    networks:
      - wallet-db-ux-network
  walletdb:
    container_name: walletdb
    image: postgres
    restart: always
    ports:
      - "5440:5432"
    environment:
      POSTGRES_wallet: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - walletdb:/var/lib/postgresql/data
    networks:
      - wallet-db-ux-network

networks: 
  wallet-db-ux-network:
    driver: bridge

volumes:
  walletdb:
  walletux: