FROM node:18

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils

WORKDIR /usr/src/app

COPY application/backend/accounting/subscription-plan-content/package.json application/backend/accounting/subscription-plan-content/yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN cd application/backend/accounting/subscription-plan-content && yarn build

EXPOSE 8013

CMD ["yarn","start"]