FROM node:18

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils

WORKDIR /usr/src/app

COPY application/backend/accounting/campaign/package.json application/backend/accounting/campaign/yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN cd application/backend/accounting/campaign && yarn build

EXPOSE 8009

CMD ["yarn","start"]