version: '3.8'

services:
  userux:
    container_name: userux
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    volumes:
      - userux:/var/lib/pgadmin
    ports:
      - "8888:80"
    networks:
      - user-db-ux-network
  userdb:
    container_name: userdb
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - userdb:/var/lib/postgresql/data
    networks:
      - user-db-ux-network

networks: 
  user-db-ux-network:
    driver: bridge

volumes:
  userdb:
  userux: