version: '3.8'

services:
  userux:
    container_name: userux
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    volumes:
      - userux:/var/lib/pgadmin
    ports:
      - "8888:80"
    networks:
      - user-db-ux-network
  userdb:
    container_name: userdb
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - userdb:/var/lib/postgresql/data
    networks:
      - user-db-ux-network
  user_app: 
    build: 
      context: .
      network: host
      dockerfile: ./dockerfile
    deploy:
      resources:
        limits:
          cpus: "12.0"
      replicas: 3
    environment:
      - PORT=8001
    command: yarn run start
    networks:
      - gateway_network
      
networks: 
  user-db-ux-network:
    driver: bridge
  gateway_network:
    external: true

volumes:
  userdb:
  userux: