FROM node:18

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils

RUN npm i -g pnpm

WORKDIR /usr/src/app

COPY ./application/backend/user/package.json pnpm-lock.yaml  ./

RUN pnpm install --frozen-lockfile

COPY ./application/backend/user .

RUN pnpm run build

CMD ["pnpm", "start"]