FROM node:18

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils

WORKDIR /usr/src/app

COPY application/backend/security/device/package.json application/backend/security/device/yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN cd application/backend/security/device && yarn build

EXPOSE 8002

CMD ["yarn","start"]