version: '3.8'

services:
  deviceux:
    container_name: deviceux
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    volumes:
      - deviceux:/var/lib/pgadmin
    ports:
      - "8889:80"
    networks:
      - devicedb-deviceux-network
  devicedb:
    container_name: devicedb
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - devicedb:/var/lib/postgresql/data
    networks:
      - devicedb-deviceux-network
  device_app: 
    build: 
      context: .
      network: host
      dockerfile: ./dockerfile
    deploy:
      replicas: 3
    environment:
      - PORT=8002
    command: yarn run start
    networks:
      - gateway_gateway-network

networks: 
  devicedb-deviceux-network:
    driver: bridge
  gateway_gateway-network:

volumes:
  devicedb:
  deviceux: