version: '3.8'

services:
  ux:
    container_name: ux
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    volumes:
      - ux:/var/lib/pgadmin
    ports:
      - "8888:80"
    networks:
      - db-ux-network
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db-ux-network

networks: 
  db-ux-network:
    driver: bridge

volumes:
  db:
  ux: