FROM node:18

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils

WORKDIR /usr/src/app

COPY application/backend/security/package.json application/backend/security/yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN cd application/backend/security && yarn build

EXPOSE 8003

CMD ["yarn","start"]