version: '3.8'

services:
  subscriptionux:
    container_name: subscriptionux
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    volumes:
      - subscriptionux:/var/lib/pgadmin
    ports:
      - "8901:80"
    networks:
      - subscription-db-ux-network
  subscriptiondb:
    container_name: subscriptiondb
    image: postgres
    restart: always
    ports:
      - "5441:5432"
    environment:
      POSTGRES_subscription: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - subscriptiondb:/var/lib/postgresql/data
    networks:
      - subscription-db-ux-network

networks: 
  subscription-db-ux-network:
    driver: bridge

volumes:
  subscriptiondb:
  subscriptionux: