FROM node:18

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils

WORKDIR /usr/src/app

COPY application/backend/security/dossier/package.json application/backend/security/dossier/yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN cd application/backend/security/dossier && yarn build

EXPOSE 8004

CMD ["yarn","start"]