version: '3.8'

services:
  dossierux:
    container_name: dossierux
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    volumes:
      - dossierux:/var/lib/pgadmin
    ports:
      - "8892:80"
    networks:
      - dossier-db-ux-network
  dossierdb:
    container_name: dossierdb
    image: postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_dossier: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - dossierdb:/var/lib/postgresql/data
    networks:
      - dossier-db-ux-network
  dossier_app: 
    build: 
      context: .
      network: host
      dockerfile: ./dockerfile
    deploy:
      replicas: 3
    environment:
      - PORT=8004
    command: yarn run start
    networks:
      - gateway_gateway-network

networks: 
  dossier-db-ux-network:
    driver: bridge
  gateway_gateway-network:

volumes:
  dossierdb:
  dossierux: