version: '3.8'

services:
  meisi-thesis-application-backend-dispatch-rabbit_mq:
    container_name: meisi-thesis-application-backend-dispatch-rabbit_mq
    image: rabbitmq:3.12-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge