version: '3.8'

services:
  bookux:
    container_name: bookux
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    volumes:
      - bookux:/var/lib/pgadmin
    ports:
      - "8893:80"
    networks:
      - book-db-ux-network
  bookdb:
    container_name: bookdb
    image: postgres
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_book: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - bookdb:/var/lib/postgresql/data
    networks:
      - book-db-ux-network
  book_app: 
    build: 
      context: .
      network: host
      dockerfile: ./dockerfile
    deploy:
      replicas: 3
    environment:
      - PORT=8005
    command: yarn run start
    networks:
      - gateway_network

networks: 
  book-db-ux-network:
    driver: bridge
  gateway_network:
    external: true

volumes:
  bookdb:
  bookux: